### ISSUE TITLE
关于AIS数据问题

### ISSUE THREAD

**Issue by ccbbzz** [Chengfeng-Jia/intent_aware_prediction#1]
想问一下您论文中关于长江口AIS数据是怎么下载或申请的，非常感谢！

**Comment by Chengfeng-Jia** [comment]
您好，AIS数据一般很难开放获取，如有需要可以下载美国AIS公开数据集。感谢提问！

**Comment by ccbbzz** [comment]
非常感谢您的回答，那我就用那些公开的吧。
那如何能快速找到，那些船舶密集或航道或港口区域吗？

**Comment by Chengfeng-Jia** [comment]
你可以试一下geohash，或者如果能提前知道哪些地方密集的话就更方便了

**Comment by ccbbzz** [comment]
好的！非常感谢您的回答
